spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Bugfix_admin
    username: postgres
    password: ${POSTGRES_PASS}
  jmx:
    default-domain: ex-emp
server:
  servlet:
    context-path: /ex-emp
